@startuml
class Course {
    - _students: Student[]
    - _lecturer: Lecturer
    - _minStudentCount: number
    - _topics: string[]

    + constructor(students: Student[], lecturer: Lecturer, minStudentCount: number, topics: string[])
    + addStudent(student)
    + addLecturer(lecturer)
    + lecturer(): Lecturer | null
    + students(): Student[]
    + canStart(): bool
}
@enduml